# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 626)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.batch_button = QtWidgets.QPushButton(self.centralwidget)
        self.batch_button.setObjectName("batch_button")
        self.gridLayout.addWidget(self.batch_button, 1, 5, 1, 1)
        self.progress_layout = QtWidgets.QHBoxLayout()
        self.progress_layout.setObjectName("progress_layout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progress_layout.addWidget(self.progressBar)
        self.gridLayout.addLayout(self.progress_layout, 5, 0, 1, 3)
        self.input_layout = QtWidgets.QHBoxLayout()
        self.input_layout.setObjectName("input_layout")
        self.input_label = QtWidgets.QLabel(self.centralwidget)
        self.input_label.setObjectName("input_label")
        self.input_layout.addWidget(self.input_label)
        self.input_path = QtWidgets.QLabel(self.centralwidget)
        self.input_path.setText("")
        self.input_path.setObjectName("input_path")
        self.input_layout.addWidget(self.input_path)
        self.input_button = QtWidgets.QPushButton(self.centralwidget)
        self.input_button.setObjectName("input_button")
        self.input_layout.addWidget(self.input_button)
        self.gridLayout.addLayout(self.input_layout, 0, 0, 1, 3)
        self.output_layout = QtWidgets.QHBoxLayout()
        self.output_layout.setObjectName("output_layout")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setObjectName("output_label")
        self.output_layout.addWidget(self.output_label)
        self.output_path = QtWidgets.QLabel(self.centralwidget)
        self.output_path.setText("")
        self.output_path.setObjectName("output_path")
        self.output_layout.addWidget(self.output_path)
        self.output_button = QtWidgets.QPushButton(self.centralwidget)
        self.output_button.setObjectName("output_button")
        self.output_layout.addWidget(self.output_button)
        self.gridLayout.addLayout(self.output_layout, 0, 3, 1, 3)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 4)
        self.target_label = QtWidgets.QLabel(self.centralwidget)
        self.target_label.setObjectName("target_label")
        self.gridLayout.addWidget(self.target_label, 1, 0, 1, 1)
        self.output_box = QtWidgets.QGroupBox(self.centralwidget)
        self.output_box.setObjectName("output_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.output_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.number_lcd = QtWidgets.QLCDNumber(self.output_box)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.number_lcd.setPalette(palette)
        self.number_lcd.setStyleSheet("color:black;")
        self.number_lcd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.number_lcd.setDigitCount(7)
        self.number_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.number_lcd.setProperty("intValue", 0)
        self.number_lcd.setObjectName("number_lcd")
        self.gridLayout_3.addWidget(self.number_lcd, 0, 2, 1, 1)
        self.number_label = QtWidgets.QLabel(self.output_box)
        self.number_label.setObjectName("number_label")
        self.gridLayout_3.addWidget(self.number_label, 0, 1, 1, 1)
        self.score_lcd = QtWidgets.QLCDNumber(self.output_box)
        self.score_lcd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.score_lcd.setDigitCount(3)
        self.score_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.score_lcd.setProperty("intValue", 0)
        self.score_lcd.setObjectName("score_lcd")
        self.gridLayout_3.addWidget(self.score_lcd, 0, 4, 1, 1)
        self.score_label = QtWidgets.QLabel(self.output_box)
        self.score_label.setObjectName("score_label")
        self.gridLayout_3.addWidget(self.score_label, 0, 3, 1, 1)
        self.output_widget = QtWidgets.QWidget(self.output_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_widget.sizePolicy().hasHeightForWidth())
        self.output_widget.setSizePolicy(sizePolicy)
        self.output_widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid;\n"
"border-color: rgb(58, 58, 58);")
        self.output_widget.setObjectName("output_widget")
        self.gridLayout_3.addWidget(self.output_widget, 1, 1, 1, 4)
        self.gridLayout.addWidget(self.output_box, 2, 3, 1, 3)
        self.input_box = QtWidgets.QGroupBox(self.centralwidget)
        self.input_box.setObjectName("input_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.input_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.threshold_label = QtWidgets.QLabel(self.input_box)
        self.threshold_label.setObjectName("threshold_label")
        self.gridLayout_2.addWidget(self.threshold_label, 0, 0, 1, 1)
        self.threshold_slider = QtWidgets.QSlider(self.input_box)
        self.threshold_slider.setMaximum(255)
        self.threshold_slider.setProperty("value", 240)
        self.threshold_slider.setOrientation(QtCore.Qt.Horizontal)
        self.threshold_slider.setObjectName("threshold_slider")
        self.gridLayout_2.addWidget(self.threshold_slider, 0, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.input_box)
        self.spinBox.setMaximum(255)
        self.spinBox.setProperty("value", 240)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 0, 2, 1, 1)
        self.input_widget = QtWidgets.QWidget(self.input_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_widget.sizePolicy().hasHeightForWidth())
        self.input_widget.setSizePolicy(sizePolicy)
        self.input_widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid;\n"
"border-color: rgb(58, 58, 58);")
        self.input_widget.setObjectName("input_widget")
        self.gridLayout_2.addWidget(self.input_widget, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.input_box, 2, 0, 1, 3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.position_button = QtWidgets.QPushButton(self.centralwidget)
        self.position_button.setObjectName("position_button")
        self.horizontalLayout_4.addWidget(self.position_button)
        self.marker_button = QtWidgets.QPushButton(self.centralwidget)
        self.marker_button.setObjectName("marker_button")
        self.horizontalLayout_4.addWidget(self.marker_button)
        self.score_button = QtWidgets.QPushButton(self.centralwidget)
        self.score_button.setObjectName("score_button")
        self.horizontalLayout_4.addWidget(self.score_button)
        self.output_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.output_file_button.setObjectName("output_file_button")
        self.horizontalLayout_4.addWidget(self.output_file_button)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 3, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.spinBox.valueChanged['int'].connect(self.threshold_slider.setValue)
        self.threshold_slider.valueChanged['int'].connect(self.spinBox.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.batch_button.setText(_translate("MainWindow", "一括処理"))
        self.input_label.setText(_translate("MainWindow", "入力元"))
        self.input_button.setText(_translate("MainWindow", "参照"))
        self.output_label.setText(_translate("MainWindow", "出力先"))
        self.output_button.setText(_translate("MainWindow", "参照"))
        self.target_label.setText(_translate("MainWindow", "処理対象"))
        self.output_box.setTitle(_translate("MainWindow", "出力ファイル"))
        self.number_label.setText(_translate("MainWindow", "学籍番号"))
        self.score_label.setText(_translate("MainWindow", "採点結果"))
        self.input_box.setTitle(_translate("MainWindow", "入力ファイル"))
        self.threshold_label.setText(_translate("MainWindow", "二極化閾値"))
        self.position_button.setText(_translate("MainWindow", "位置マーカー検出"))
        self.marker_button.setText(_translate("MainWindow", "解答マーカー検出"))
        self.score_button.setText(_translate("MainWindow", "採点"))
        self.output_file_button.setText(_translate("MainWindow", "書き出し"))

